SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS FormattedDate
FROM REST_REVIEW AS RR
JOIN MEMBER_PROFILE AS MP ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE RR.MEMBER_ID = (
  SELECT MEMBER_ID
  FROM (
    SELECT MEMBER_ID, COUNT(*) AS Count
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY Count DESC
    LIMIT 1
  ) AS SubQuery
)
ORDER BY RR.REVIEW_DATE;



SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, SUM(FO.AMOUNT * FP.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT AS FP
JOIN FOOD_ORDER AS FO ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE DATE_FORMAT(FO.PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY FP.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID ASC;

SELECT FP.FLAVOR
FROM FIRST_HALF AS FP
JOIN JULY ON FP.FLAVOR = JULY.FLAVOR
GROUP BY FP.FLAVOR
ORDER BY (FP.TOTAL_ORDER + SUM(JULY.TOTAL_ORDER)) DESC
LIMIT 3;